steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/life-calendar-frontend/$COMMIT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/life-calendar-frontend/$COMMIT_SHA",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "life-calendar-frontend",
        "--image",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/life-calendar-frontend/$COMMIT_SHA",
        "--region",
        "asia-northeast1-docker",
      ]

images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/life-calendar-frontend/$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
